name: Shared Setup
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v3
    - uses: Swatinem/rust-cache@v2
    - run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
